//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOK.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class satıslar
    {
        public int satıs_id { get; set; }
        public Nullable<int> urun_id { get; set; }
        public Nullable<int> musteri_id { get; set; }
        public Nullable<int> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    
        public virtual musteriler musteriler { get; set; }
        public virtual urunler urunler { get; set; }
    }
}
